---
- name: Run web-app role
  hosts: web 
  remote_user: root
  become: yes
  host_key_checking: false
  roles:
    - { role: web-app }

- name: Run nginx balancer role
  hosts: nginx
  remote_user: root
  become: yes
  host_key_checking: false
  roles:
    - { role: nginx }
