---

- src: teralex79.exam_ansible_docker_role
  path: roles
  name: role_docker

- src: teralex79.exam_ansible_web_app_role
  path: roles
  name: role_web_app
 
- src: teralex79.exam_ansible_nginx_role
  path: roles
  name: role_nginx
