---

- src: teralex79.exam_ansible_docker_role
  path: roles
  name: docker

- src: teralex79.exam_ansible_web_app_role
  path: roles
  name: web-app
 
- src: teralex79.exam_ansible_nginx_role
  path: roles
  name: nginx
