---

- src: teralex79.exam_ansible_docker_role
  path: roles
  name: role_docker
#git@github.com:teralex79/exam-ansible-docker-role.git

- src: git@github.com:teralex79/exam-ansible-web-app-role.git
  path: roles
  name: role_web_app
 
- src: git@github.com:teralex79/exam-ansible-nginx-role.git
  path: roles
  name: role_nginx
