[all]
  [web]
#    CentOS_web1 ansible_host=192.168.56.103 ansible_user=root ansible_connection=ssh ansible_ssh_private_key_file=~/.ssh/deb1_rsa docker_app_port=5001 docker_name=web_app_1
#    CentOS_web1 ansible_host=192.168.56.106 ansible_user=root ansible_connection=ssh ansible_ssh_private_key_file=~/.ssh/deb1_rsa docker_app_port=5001 docker_name=web_app_1
    CentOS_web1 
#    CentOS_web2 ansible_host=192.168.56.104 ansible_user=root ansible_connection=ssh ansible_ssh_private_key_file=~/.ssh/deb1_rsa docker_app_port=5002 docker_name=web_app_2
    CentOS_web2 
#    Debian_web3 ansible_host=192.168.56.105 ansible_user=root ansible_connection=ssh ansible_ssh_private_key_file=~/.ssh/deb1_rsa docker_app_port=5003 docker_name=web_app_3
    Debian_web3 
  [nginx]
#    nginx_balancer ansible_host=192.168.56.101 ansible_user=root ansible_connection=ssh ansible_ssh_private_key_file=~/.ssh/deb1_rsa docker_name=nginx_balancer
    CentOS_nginx_balancer 
